/* eslint-disable prettier/prettier */
export const SCHEDULE = [
    {
        weekDay: 'Понедельник',
        fromTime: '17:00',
        toTime: '21:00',
        place: 'СевСтена Петра',
        type: 'BOULDER',
    },
    {
        weekDay: 'Среда',
        fromTime: '17:00',
        toTime: '21:00',
        place: 'Неолит',
        type: 'BOULDER',
    },
    {
        weekDay: 'Четверг',
        fromTime: '15:00',
        toTime: '21:00',
        place: 'Неолит Питаль Н.П.',
        type: 'BOULDER',
    },
    {
        weekDay: 'Пятница',
        fromTime: '16:30',
        toTime: '21:00',
        place: 'Неолит',
        type: 'BOULDER',
    },
    {
        weekDay: 'Суббота',
        fromTime: '13:00',
        toTime: '17:00',
        place: 'СевСтена',
        type: 'LEAD',
    },
    {
        weekDay: 'Понедельник',
        fromTime: '9:00',
        toTime: '14:00',
        type: 'SCHOOL',
    },
    {
        weekDay: 'Вторник',
        fromTime: '9:00',
        toTime: '14:00',
        type: 'SCHOOL',
    },
    {
        weekDay: 'Среда',
        fromTime: '9:00',
        toTime: '14:00',
        type: 'SCHOOL',
    },
    {
        weekDay: 'Четверг',
        fromTime: '9:00',
        toTime: '14:00',
        type: 'SCHOOL',
    },
    {
        weekDay: 'Пятница',
        fromTime: '9:00',
        toTime: '14:00',
        type: 'SCHOOL',
    },
    {
        weekDay: 'Вторник',
        fromTime: '16:00',
        toTime: '17:30',
        place: 'Рисование',
        type: 'HOBBY',
    },
];